parameters:
  boekkooi.amqp.consumer.queue_locator.class: Boekkooi\Bundle\AMQP\QueueLocator\ContainerLocator

services:
  ## Consumtion related ##
  boekkooi.amqp.abstract.consumer.queue_locator:
    class: %boekkooi.amqp.consumer.queue_locator.class%
    arguments:
      - @service_container
    abstract: true
    public: false
