parameters:
  boekkooi.amqp.command.handle.class: Boekkooi\Bundle\AMQP\Command\HandleCommand

services:
  boekkooi.amqp.command.handle:
    class: %boekkooi.amqp.command.handle.class%
    arguments:
      - @tactician.commandbus
      - @service_container
    tags:
      -  { name: console.command }
