language: php

php:
  - 5.5
  - 5.6
  - 7.0

matrix:
  include:
    - php: 5.5
      env: |
        COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
        COVERAGE="--coverage-clover=coverage.xml"
    - php: 5.6
      env: SYMFONY_VERSION="2.7.*"
    - php: 5.6
      env: SYMFONY_VERSION="2.8.*"
    - php: 5.6
      env: SYMFONY_VERSION="3.0.*"
  allow_failures:
    - php: 7.0

install:
  - echo "extension = amqp.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry wget http://get.sensiolabs.org/php-cs-fixer.phar -O php-cs-fixer.phar

before_script:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require symfony/symfony:${SYMFONY_VERSION} --no-update; fi
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction

script:
  - vendor/bin/phpunit ${COVERAGE}
  - php php-cs-fixer.phar fix src/ --level=psr2 --dry-run

after_script:
  - if [[ "${COVERAGE}" != "" ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "${COVERAGE}" != "" ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi
